FROM spotify_base:latest

WORKDIR /app

# Install API dependencies
COPY docker/requirements/requirements-fastapi.txt .
RUN pip install --no-cache-dir -r requirements-fastapi.txt

# Copy the API code
COPY ./ml_pipeline /app/ml_pipeline

EXPOSE 8080

CMD ["uvicorn", "ml_pipeline.api.main:app", "--host", "0.0.0.0", "--port", "8080", "--reload"]