services:
  # Base evn for all prosses that uses Python
  spotify_base:
    build:
      context: .
      dockerfile: ./docker/base/Dockerfile.spotify_base
    image: spotify_base:latest
    healthcheck:
      test: ["CMD", "python", "--version"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - ml-network
    command: ["tail", "-f", "/dev/null"]
    container_name: spotify_base

  # PostgreSQL database for MLflow tracking
  # Shared PostgreSQL database for both Dagster and MLflow
  postgres:
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile.postgres
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin_password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready  -U postgres -d postgres "]
      interval: 5s
      retries: 5
      start_period: 5s
      timeout: 5s
    networks:
      - ml-network
    container_name: postgres

  # MLflow tracking server
  mlflow:
    build:
      context: .
      dockerfile: ./docker/mlflow/Dockerfile.mlflow
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      MLFLOW_TRACKING_URI: "postgresql://mlflow_user:mlflow_password@postgres:5432/mlflow"
      MLFLOW_DEFAULT_ARTIFACT_ROOT: "/mlflow/artifacts"
    volumes:
      - mlflow_data:/mlflow
    ports:
      - "5000:5000"
    networks:
      - ml-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    command: >
      mlflow server 
      --backend-store-uri postgresql://mlflow_user:mlflow_password@postgres:5432/mlflow?sslmode=disable
      --default-artifact-root /mlflow/artifacts 
      --host 0.0.0.0
    container_name: mlflow-server

  # LakeFS for data versioning and management
  lakefs:
    image: treeverse/lakefs:latest
    container_name: lakefs
    ports:
      - "8000:8000"
    environment:
      - LAKEFS_DATABASE_TYPE=postgres
      - LAKEFS_DATABASE_POSTGRES_CONNECTION_STRING=postgres://lakefs_user:lakefs_password@postgres:5432/lakefs?sslmode=disable
      - LAKEFS_BLOCKSTORE_TYPE=local
      - LAKEFS_BLOCKSTORE_LOCAL_PATH=/home/lakefs/data
      - LAKEFS_AUTH_ENCRYPT_SECRET_KEY=${LAKEFS_AUTH_ENCRYPT_SECRET_KEY}
      - LAKEFS_ADMIN_ACCESS_KEY_ID=${LAKEFS_ADMIN_ACCESS_KEY}
      - LAKEFS_ADMIN_SECRET_ACCESS_KEY=${LAKEFS_ADMIN_SECRET_KEY}
      - LAKEFS_BLOCKSTORE_LOCAL_IMPORT_ENABLED=true
      - LAKEFS_SETUP_ADMIN_USER=true
      - LAKEFS_SETUP_ADMIN_NAME=admin
    volumes:
      - lakefs_data:/home/lakefs/data
    user: root
    networks:
      - ml-network
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8000/healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  # Dagster daemon for scheduling and sensor execution
  dagster-daemon:
    build:
      context: .
      dockerfile: ./docker/dagster/Dockerfile.dagster
    depends_on:
      spotify_base:
        condition: service_healthy
      mlflow:
        condition: service_healthy
      postgres:
        condition: service_healthy
    restart: on-failure
    environment:
      DAGSTER_POSTGRES_URL: "postgresql://dagster:dagster_password@postgres:5432/dagster?sslmode=disable"
      DAGSTER_HOME: "/opt/dagster/dagster_home"
      LAKEFS_ACCESS_KEY_ID: ${LAKEFS_ADMIN_ACCESS_KEY}
      LAKEFS_SECRET_ACCESS_KEY: ${LAKEFS_ADMIN_SECRET_KEY}
      LAKEFS_ENDPOINT: "http://lakefs:8000"
    volumes:
      - dagster_data:/opt/dagster/dagster_home
      - ./ml_pipeline:/opt/dagster/app/ml_pipeline
      - /Users/level3/.kaggle:/root/.kaggle
    healthcheck:
      test: ["CMD", "pgrep", "-f", "dagster-daemon"]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 30s
    command: >
      dagster-daemon run
    container_name: dagster-daemon
    networks:
      - ml-network
  
  # Dagster webserver
  dagster-webserver:
    build:
      context: .
      dockerfile: ./docker/dagster/Dockerfile.dagster
    depends_on:
      dagster-daemon:
        condition: service_healthy
      postgres:
        condition: service_started
    ports:
      - "3000:3000"
    environment:
      DAGSTER_POSTGRES_URL: "postgresql://dagster:dagster_password@postgres:5432/dagster?sslmode=disable"
      DAGSTER_HOME: "/opt/dagster/dagster_home"
      DAGSTER_WEBSERVER_RELOAD: "true"
      DAGSTER_WEBSERVER_RELOAD_INTERVAL: "1"
      DAGSTER_WEBSERVER_RELOAD_DIRS: "/opt/dagster/app/ml_pipeline"
      LAKEFS_ACCESS_KEY_ID: ${LAKEFS_ADMIN_ACCESS_KEY}
      LAKEFS_SECRET_ACCESS_KEY: ${LAKEFS_ADMIN_SECRET_KEY}
      LAKEFS_ENDPOINT: "http://lakefs:8000"
    volumes:  
      - ./ml_pipeline:/opt/dagster/app/ml_pipeline
      - ./config/workspace.yaml:/opt/dagster/app/workspace.yaml
      - ./config/local/dagster.yaml:/opt/dagster/dagster_home/dagster.yaml
      - /Users/level3/.kaggle:/root/.kaggle 
    networks:
      - ml-network
    command: ["dagster-webserver","-h", "0.0.0.0", "-p", "3000"]
    container_name: dagster-webserver

  # API service 
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile.api
    container_name: spotify-api
    ports:
      - "8080:8080"
    depends_on:
      mlflow:
        condition: service_healthy
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    volumes:
      - ./ml_pipeline:/app/ml_pipeline
    networks:
      - ml-network
    command: uvicorn ml_pipeline.api.main:app --host 0.0.0.0 --port 8080 --reload

  # Frontend UI
  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile.frontend
    container_name: spotify-frontend
    ports:
      - "8501:8501"
    depends_on:
      api:
        condition: service_started
    environment:
      - API_URL=http://api:8080
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    volumes:
      - ./ml_pipeline:/app/ml_pipeline
    networks:
      - ml-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    command: streamlit run ml_pipeline/frontend/app.py --server.address 0.0.0.0 --server.port 8501

  # LakeFS setup service
  lakefs-setup:
    build:
      context: .
      dockerfile: ./docker/lakefs/Dockerfile.lakefs_setup
    networks:
      - ml-network
    environment:
      - LAKEFS_ENDPOINT=http://lakefs:8000
      - LAKEFS_ADMIN_ACCESS_KEY=${LAKEFS_ADMIN_ACCESS_KEY}
      - LAKEFS_ADMIN_SECRET_KEY=${LAKEFS_ADMIN_SECRET_KEY}
    volumes:
      - /var/lakefs_setup:/var/lakefs_setup
    depends_on:
      lakefs:
        condition: service_healthy
      postgres:
        condition: service_healthy
    restart: "no"

networks:
  ml-network:
    driver: bridge

volumes:
  postgres_data:
  mlflow_data:
  lakefs_data:
  dagster_data:
  lakefs_setup_done:

