# load_from:
#   - python_file:
#       relative_path: "ml_pipeline/__init__.py"
#       working_directory: /opt/dagster/app
#       location_name: "ml_pipeline"
#       attribute: "my_repo" 

load_from:
  - python_package:
      package_name: ml_pipeline
      working_directory: /opt/dagster/app

