FROM treeverse/lakefs:latest

RUN apk add --no-cache curl && \
    curl -L https://github.com/treeverse/lakeFS/releases/latest/download/lakectl-linux-amd64 -o /usr/local/bin/lakectl && \
    chmod +x /usr/local/bin/lakectl && \
    file /usr/local/bin/lakectl
